### PR TITLE
Add some UI

### PR DESCRIPTION
**Pull request by HugoHeneault**
Hi there, 
I'd used your site for quite a long time, and it's so powerfull I wanted to give it a proper UI. :smiley: 

Look :
ui

It could be great if you can implement it! 
I added some credits for the design, I hope you'll be ok with that. 

Best regards,

### CODE REVIEW

**Comment by HugoHeneault** [comment]
This is what was asked in #4, by the way. :)

**Comment by mow** [comment]
Hey! thank you very much :) I'm going to implement this as soon as possible

**Comment by HugoHeneault** [comment]
Hello! :)
Any hope to see this implemented online? 
Are you having issue while deploying it?

**Comment by HugoHeneault** [comment]
No news? :cry:

**Pull request merged**
